Fearture find shop by distance
phong-jack/food-ordering-nestjs pull request #2
Opened 2024-05-14 09:21 UTC by phong-jack

write feature find shop by distance
![image](https://github.com/phong-jack/food-ordering-nestjs/assets/166998963/5734ceb5-9501-426a-a198-077b55945fee)

2024-05-15 01:22 UTC, voxuanan requested changes
Please update according to feedback

2024-05-15 01:22 UTC, voxuanan commented on src/modules/shop/services/shop.service.ts
> +  async findShopByDistance(userId: number) {
- I recommend you write a methods on repository doing this (you can using Query Builder, Raw Query),
- findShopByDistance should be paginated

2024-05-15 01:22 UTC, voxuanan commented on src/modules/setting/constants/setting.constant.ts
> +export enum SETTING_KEY {
I see you prepare some potential "SETTING KEY" here, do we need to emit an event when user (shop) created to initialize the settings for them

2024-05-15 01:22 UTC, voxuanan commented on src/modules/shop/repositories/shop.repository.ts
> +
i recommend you to create base repositories (CRUD, find pagination) and extend it with each repository you have

2024-05-15 01:22 UTC, voxuanan commented on src/modules/shop/services/shop.service.ts
> +  async updateShopLocate(id: number, address: string): Promise<Shop> {
What happens if I update the shop address using the above updateShop method, do we need to update the locate?

2024-05-15 03:44 UTC, phong-jack commented on src/modules/shop/services/shop.service.ts
> +  async updateShopLocate(id: number, address: string): Promise<Shop> {
![image](https://github.com/phong-jack/food-ordering-nestjs/assets/166998963/6f40b724-30d5-4bcf-9855-96554337a8b6)
import updateShopLocate into update Shop, remove route update-shop-locate

2024-05-16 01:24 UTC, phong-jack commented on src/modules/shop/repositories/shop.repository.ts
> +
apply CRUD base

2024-05-16 01:24 UTC, phong-jack commented on src/modules/setting/constants/setting.constant.ts
> +export enum SETTING_KEY {
create event emitter for setting key

2024-05-16 01:29 UTC, merged