Fearture sync process for shop
phong-jack/food-ordering-nestjs pull request #3
Opened 2024-05-17 07:33 UTC by phong-jack

2024-05-17 10:11 UTC, anvotnm commented
Pretty good! but please update a little
Using a while loop for synchronization is fine, but let's improve it a bit.

You should create another Queue (I will call it Sync_Queue or whatever you want) for this synchronization
The process starts when you call an API that adds a job to the Sync_Queue with jobData:
{
   page: 1,
   count: 100
}

Then you write a consumer (processor)  for which this job will fetch data and make changes to your shop, etc...
if jobData.page * jobDatacount < reply.data.Total then add another job into Sync_Queue which is:
{
   page: page +1,
   count: 100
} 

Do this if your app crashes during sync, it will be able to continue the sync

2024-05-17 10:14 UTC, voxuanan commented
Pretty good! but please update a little
Using a while loop for synchronization is fine, but let's improve it a bit.

You should create another Queue (I will call it Sync_Queue or whatever you want) for this synchronization
The process starts when you call an API that adds a job to the Sync_Queue with jobData:
{
page: 1,
count: 100
}

Then you write a consumer (processor) for which this job will fetch data and make changes to your shop, etc...
if jobData.page * jobDatacount < reply.data.Total then add another job into Sync_Queue which is:
{
page: page +1,
count: 100
}

Do this if your app crashes during sync, it will be able to continue the sync

2024-05-17 10:14 UTC, voxuanan commented
Remember to assign yourself and request me as reviewers

2024-05-17 10:16 UTC, voxuanan requested changes

2024-05-17 10:16 UTC, voxuanan commented on src/common/fetch/services/fetch.service.ts
> +  async fetchShopData(): Promise<void> {
What I mentioned above is here

2024-05-20 06:54 UTC, voxuanan commented
LGTM!

2024-05-20 06:55 UTC, merged